[package]
name = "matter-iot"
version = "0.1.0"
edition = "2018"
authors = ["Kedar Sovani <kedars@gmail.com>"]
description = "Native RUST implementation of the Matter (Smart-Home) ecosystem"
repository = "https://github.com/kedars/matter-rs"
readme = "README.md"
keywords = ["matter", "smart", "smart-home", "IoT", "ESP32"]
categories = ["embedded", "network-programming"]
license = "MIT"

[lib]
name = "matter"
path = "src/lib.rs"

[features]
default = ["crypto_mbedtls"]
crypto_openssl = ["openssl", "foreign-types", "hmac", "sha2"]
crypto_mbedtls = ["mbedtls"]
crypto_esp_mbedtls = ["esp-idf-sys"]

[dependencies]
boxslab = { path = "../boxslab" }
matter_macro_derive = { path = "../matter_macro_derive" }
bitflags = "1.3"
byteorder = "1.4.3"
heapless = { version = "0.7.16", features = ["x86-sync-pool"] }
generic-array = "0.14.6"
num = "0.4"
num-derive = "0.3.3"
num-traits = "0.2.15"
log = { version = "0.4.17", features = ["max_level_debug", "release_max_level_debug"] }
env_logger = "0.10.0"
rand = "0.8.5"
esp-idf-sys = { version = "0.32", features = ["binstart"], optional = true }
openssl = { git = "https://github.com/sfackler/rust-openssl", optional = true }
foreign-types = { version = "0.3.2", optional = true }
sha2 = { version = "0.9.9", optional = true }
hmac = { version = "0.11.0", optional = true }
mbedtls = { git = "https://github.com/fortanix/rust-mbedtls", optional = true }
subtle = "2.4.1"
colored = "2.0.0"
smol = "1.3.0"
owning_ref = "0.4.1"
safemem = "0.3.3"
chrono = { version = "0.4.23", default-features = false, features = ["clock", "std"] }
async-channel = "1.8"

# to compute the check digit
verhoeff = "1"

# print QR code
qrcode = { version = "0.12", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
astro-dnssd = "0.3"

# MDNS support
[target.'cfg(target_os = "linux")'.dependencies]
lazy_static = "1.4.0"
libmdns = { version = "0.7.4" }

[[example]]
name = "onoff_light"
path = "../examples/onoff_light/src/main.rs"


[[example]]
name = "speaker"
path = "../examples/speaker/src/main.rs"
