name: PublishDryRun

on: workflow_dispatch

env:
  RUST_TOOLCHAIN: stable
  CRATE_NAME: rs-matter

jobs:
  publish_dry_run:
    name: PublishDryRun
    runs-on: ubuntu-latest
    steps:
      - name: Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy, rust-src

      - name: Install libdbus
        run: sudo apt-get install -y libdbus-1-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: PublishDryRun
        run: cargo publish -p rs-matter --dry-run
